// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtabgGnlGreRB_lKnkJWlG_hsc3J4NLBk',
    appId: '1:710802048781:web:59d239f67b2759f9351244',
    messagingSenderId: '710802048781',
    projectId: 'smartdefender-51842',
    authDomain: 'smartdefender-51842.firebaseapp.com',
    databaseURL: 'https://smartdefender-51842-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdefender-51842.appspot.com',
    measurementId: 'G-TWDD14ZDHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJ2gBkdXfsQwsjdbCWPK-8HA7Li54KHg',
    appId: '1:710802048781:android:4cab2cbdd6ecba29351244',
    messagingSenderId: '710802048781',
    projectId: 'smartdefender-51842',
    databaseURL: 'https://smartdefender-51842-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdefender-51842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzCY2n4VepI1Cug6vVoi1ZWp4bSaZm_fs',
    appId: '1:710802048781:ios:933123cdc9dfb74b351244',
    messagingSenderId: '710802048781',
    projectId: 'smartdefender-51842',
    databaseURL: 'https://smartdefender-51842-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdefender-51842.appspot.com',
    iosBundleId: 'com.example.smartDefender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzCY2n4VepI1Cug6vVoi1ZWp4bSaZm_fs',
    appId: '1:710802048781:ios:933123cdc9dfb74b351244',
    messagingSenderId: '710802048781',
    projectId: 'smartdefender-51842',
    databaseURL: 'https://smartdefender-51842-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartdefender-51842.appspot.com',
    iosBundleId: 'com.example.smartDefender',
  );
}
